<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<!DOCTYPE html>
<html lang="en-GB">
<head>
	<title>Movie details, Release dates, Scrubflix information about movies</title>
	<!-- ------------------------------------------------------------- -->
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<!-- ------------------------------------------------------------- -->
	<meta name="description" content="Scrublix is a web application providing information about movies" />
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="ROBOTS" content="INDEX,FOLLOW" />
	<meta http-equiv="content-language" content="en-gb" />
	<!-- ------------------------------------------------------------- -->

	<!-- Custom Javascript -->

	<!-- SCRIPT TO CHANGE THEME -->
	<script>
		function swapStyleSheet(sheet) {
			document.getElementById('pageStyle').setAttribute('href', sheet);
		}
	</script>
	<!-- SCRIPT TO CHANGE THEME -->

	<!-- Bootstrap -->

	<!-- Custom CSS -->
	<link rel="icon" href="https://cdn3.iconfinder.com/data/icons/multimedia/100/play_movie_3-512.png" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
	<link id="pageStyle" rel="stylesheet" type="text/css" href="style.css" />
	<link href="css/home-page.css" rel="stylesheet" type="text/css" />
	<!-- ------------------------------------------------------------- -->
</head>
<body id="background-image">
	<form id="formScrubfixhome" runat="server">
		<!-- Navbar -->
		<nav class="navbar navbar-inverse">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mainNavBar">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a href="Default.aspx" class="navbar-brand">SCRUBFLIX</a>
				</div>
				<div class="collapse navbar-collapse" id="mainNavBar">
					<ul class="nav navbar-nav">
						<li class="active"><a href="#">Movies</a></li>
						<li><a href="top20.aspx">Top20</a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Change Theme <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li onclick="swapStyleSheet('themes/gold.css')">Gold</li>
								<li onclick="swapStyleSheet('themes/green.css')">Green</li>
								<li onclick="swapStyleSheet('style.css')">Default</li>
							</ul>
						</li>
						<li><a href="genres.html">Genres</a></li>
					</ul>
					<div class="search-container">
						<input class="inputText" type="text" placeholder="Search.." name="search">
						<button type="submit"><i class="fa fa-search"></i></button>
					</div>
				</div>
			</div>
		</nav>

		<!--  **************************************************** CAROUSEL **************************** -->
		<div class="fitScreen">
			<div id="myCarousel" class="carousel slide" data-ride="carousel">

				<!-- Wrapper for slides -->
				<div class="carousel-inner">
					<div class="item active">
						<div class="mySlides w3-display-container w3-center">
							<img src="images/carousel1.jpg" style="width: 100%; max-height: 500px" alt="Star Wars The Last Jedi">
						</div>
					</div>
					<div class="item">
						<div class="mySlides w3-display-container w3-center">
							<img src="images/carousel2.jpg" style="width: 100%; max-height: 500px" alt="Maze Runner the Deatrh Cure">
						</div>
					</div>

					<div class="item">
						<div class="mySlides w3-display-container w3-center">
							<img src="images/carousel3.jpg" style="width: 100%; max-height: 500px" alt="Justice League">
						</div>
					</div>
				</div>
				<!-- Left and right controls -->
				<a class="left carousel-control" href="#myCarousel" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="right carousel-control" href="#myCarousel" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>
		</div>
		<!--  **************************************************** CAROUSEL **************************** -->

		<!---------------- Dynamic Data Driven Code - Output Generated by C#.NET Data Access to MySQL Database ---------------->
		<div class="line-space"></div>
		<div class="flex-wrap">
			<% Response.Write(__OutputHTML); %>
		</div>
		<div class="line-space"></div>
		<!---------------- Dynamic Data Driven Code - Output Generated by C#.NET Data Access to MySQL Database ---------------->

		<div class="footer">proudly coded</div>

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	</form>
</body>
</html>
